"""add_drone_model_and_update_order_fields

Revision ID: 4c6578a8d827
Revises: 
Create Date: 2026-02-25 00:12:05.207639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6578a8d827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Dev migration: old orders used lat/lon which are incompatible with the new
    # 4-coordinate schema. Truncate to avoid NOT NULL constraint violations.
    op.execute("TRUNCATE TABLE orders RESTART IDENTITY CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('start_lat', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('start_lon', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('end_lat', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('end_lon', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('distance_km', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('estimated_flight_time', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.Enum('pending', 'flying', 'delivered', 'lost', 'damaged', name='orderstatus'), nullable=False))
    op.add_column('orders', sa.Column('drone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_drone_id'), 'orders', ['drone_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'drones', ['drone_id'], ['id'])
    op.drop_column('orders', 'lon')
    op.drop_column('orders', 'lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_drone_id'), table_name='orders')
    op.drop_column('orders', 'drone_id')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'estimated_flight_time')
    op.drop_column('orders', 'distance_km')
    op.drop_column('orders', 'end_lon')
    op.drop_column('orders', 'end_lat')
    op.drop_column('orders', 'start_lon')
    op.drop_column('orders', 'start_lat')
    # ### end Alembic commands ###
